name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Version and Publish Packages
        run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Required for publishing to npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for creating GitHub releases